version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: FormularioDatos
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FormularioDatos-php-fpm
    volumes:
      - ./app:/var/www/html